---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: bandwidth-limit-acc

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: bandwidth-limit
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: bandwidth-limit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bandwidth-limit
subjects:
- kind: ServiceAccount
  name: bandwidth-limit-acc
  namespace: bandwidth-limit