apiVersion: v1
kind: Pod
metadata:
  name: sleep
spec:
  nodeSelector:
    imagecache: "true"
  tolerations:
  - key: "noSchedule"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: sleep
    image: dustise/sleep:v0.9.5